name: build and test feature branch
on: #Eventos
    push:
        branches:
            - feature/*
jobs: #Construir el ambiente
    build-feature:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: pull and chekout form git repository
              run: | 
                echo "pulling and cheking out form git repository"

            - name: Setup Node.js 18
              uses: actions/setup-node@v3
              with:
                node-version: '18'
                cache: 'npm'
            
            - name: Install Dependencies
              run: npm install
            
            - name: Install Angular CLI
              run: npm install -g @angular/cli@latest
            
            - name: Run Tests
              run: |
               ng test --watch=false
               ng build
               echo "Tests Passed"
            